server:
  port: 9002
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /inspection-plan

eureka:
  client:
    service-url:
      defaultZone: http://121.199.19.240:8761/eureka/,http://121.199.19.240:8762/eureka/
  instance:
    instance-id: inspection-plan #实例名

#项目信息
info:
  company.name: com.ovopark
  company.addr: China SuZhou
  company.tel: 17621142248
  app.name: -center
  app.desc: mic-server-cloud
  author: alan.liu

spring:
  datasource:
    name: shopwebdb
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      jdbc-url: jdbc:mysql://121.43.123.76:3306/shopwebdb?characterEncoding=UTF-8&useUnicode=true&useSSL=false
      username: root
      password: WUmtKNTGRiSLXLGr
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 1
    host: 121.43.123.76
    port: 36379
    password: ovopark2016  # Redis服务器连接密码（默认为空）
    timeout: 3000 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ovopark.po  # 注意：对应实体类的路径


logging:
  file:
    path: /Users/liuhao/wdzIdeaProject/inspection-plan/log

ovopark:
  sso:
    server:
      url: http://47.96.139.143:8819

config:
  expiredTime: 2592000000

shopjob:
  url: http://116.62.15.85:8088/xxl-job-admin
  executorId: 7

websocket:
  url: http://121.43.123.76:8088/shopweb-websocket/websocket/sendMessageToUser

jpush:
  url: http://121.43.123.76:8088/shopweb-support/xinfaMission/sendCrmjPush